site_name: FWXVI Strategy Documentation
site_url: https://uw-midsun.github.io/fwxvi_strategy/
theme:
  name: material
  logo: assets/midsun_logo.png
  favicon: assets/midsun_logo.png
  palette:
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Guides:
    - Our Math: guides/strategy_arch.md
  - API Reference:
      - simulation/: api/simulation.md

watch:
  - simulation